POST http://localhost:8080/api/citas
Content-Type: application/json

{
  "paciente": {
    "nombre": "Don Roberto",
    "tipo": "NUEVO"
  },
  "fechaHora": "2026-03-25T10:00:00",
  "especialidad": "CARDIOLOGO"
}