spring.application.name=clinica
clinica.horario.apertura=06:00
clinica.horario.cierre=20:00


spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_db
spring.datasource.username=postgres
spring.datasource.password=admin2908
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false